controller_list:
  - name: fake_antenna_controller
    joints:
      - j_ant_pan
      - j_ant_tilt
  - name: fake_arm_controller
    joints:
      - j_shou_yaw
      - j_shou_pitch
      - j_prox_pitch
      - j_dist_pitch
      - j_hand_yaw
      - j_scoop_yaw
  - name: fake_limbs_controller
    joints:
      - j_shou_yaw
      - j_shou_pitch
      - j_prox_pitch
      - j_dist_pitch
      - j_hand_yaw
  - name: fake_grinder_controller
    joints:
      - j_shou_yaw
      - j_shou_pitch
      - j_prox_pitch
      - j_dist_pitch
      - j_hand_yaw
      - j_grinder
initial:  # Define initial robot poses.
  - group: arm
    pose: default_pose